version: '3.7'
services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=dog
      - POSTGRES_PASSWORD=cat